### ISSUE TITLE
pam_hbac(sshd:account): Cannot find user (SLES 11.4)

### ISSUE THREAD

**Issue by brotaxt** [jhrozek/pam_hbac#104] opened 2017-11-17 11:20 UTC
Hi,

first of all many thanks for your work! 

I know Suse distributions (openSUSE / SLES) arent officially supported.
Nevertheless Iam trying to get it running on SLES 11 SP4.

I've successfully compiled the module on my SLES-Server, but unfortunately I got some trouble with the connection.

I've added the module to the /etc/pam.d/common-account config file as follows:

account requisite       pam_unix2.so
account sufficient      pam_localuser.so
account required        pam_ldap.so     use_first_pass

account required        pam_hbac.so debug

This seems to work, but the module cant find the appropriate user:

Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): debug option found
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): config file: /etc/pam_hbac.conf
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): URI: ldap://xxxxxxxxxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): search base: dc=xxxxxxx,dc=xxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): bind dn: uid=admin,cn=users,cn=accounts,dc=xxxxxxx,dc=xxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): ca cert: /etc/openldap/cacerts/ipa.crt
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): host name: xxxxxxx.xxxxxxx.xxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): ph_init: OK
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): URI: ldap://xxxxxxx.xxxxxxx.xxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): search base: dc=xxxxxxx,dc=xxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): bind DN: uid=admin,cn=users,cn=accounts,dc=xxxxxxx,dc=xxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): client hostname: xxxxxxx.xxxxxxx.xxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): cert: /etc/openldap/cacerts/ipa.crt
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): timeout 5
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): CA cert set to: /etc/openldap/cacerts/ipa.crt
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): START TLS result: Success(0), Start TLS request accepted.Server willing to negotiate SSL.
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): ph_connect: OK
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): Service: sshd
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): User: xyz
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): Tty: ssh
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): Ruser: (not available)
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): Rhost: xxxxxxx.xxxxxxx.xxxx
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): Cannot find user xyz
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): Did not find user xyz
Nov 17 12:05:32 hostname sshd[10595]: pam_hbac(sshd:account): returning [10]: User not known to the underlying authentication module

Anyone got an idea?

Many thanks in advance!

Best regards!

**Comment by jhrozek** [comment] 2017-11-18 19:54
The first thing should be to check if “id user” works that’s pretty much what the module does to resolve the user

**Comment by brotaxt** [comment] 2017-11-20 08:04
Hi  jhrozek,

thanks for your response.

id $USER works as expected

Best regards!

**Comment by jhrozek** [comment] 2017-11-20 10:53
OK, in that case I would check the IPA DS server logs around the time you're running pam_hbac. I would check:
1) The bind DN and the user in the logs
2) The query itself

But I'm suprised, because internally pam_hbac just calls getpwnam()..

the other thing to try would be to run some minimal PAM client and ltrace or strace it to see exactly what's going on..

**Comment by jhrozek** [comment] 2017-11-20 10:58
Also, what IPA versions do you use? Do you use the "domain resolution order" ?

**Comment by brotaxt** [comment] 2017-11-20 12:43
We're using Red Hat IDM Version 4.4.0, the domain resolution order option is not set.

I dont know why the user cant be found, the searchbase seems to be correct!?

[20/Nov/2017:13:36:37.365777615 +0100] conn=25 fd=110 slot=110 connection from CLIENT_IP to IPA_SERVER_IP
[20/Nov/2017:13:36:37.366127503 +0100] conn=25 op=0 EXT oid="1.3.6.1.4.1.1466.20037" name="start_tls_plugin"
[20/Nov/2017:13:36:37.366176000 +0100] conn=25 op=0 RESULT err=0 tag=120 nentries=0 etime=0
[20/Nov/2017:13:36:37.370898665 +0100] conn=25 TLS1.0 256-bit AES
[20/Nov/2017:13:36:37.371044757 +0100] conn=25 op=1 BIND dn="uid=USERNAME,cn=users,cn=accounts,dc=DOMAIN,dc=de" method=128 version=3
[20/Nov/2017:13:36:37.371958223 +0100] conn=25 op=1 RESULT err=0 tag=97 **nentries=0** etime=0 dn="uid=USERNAME,cn=users,cn=accounts,dc=DOMAIN,dc=de"

**Comment by jhrozek** [comment] 2017-11-20 13:33
There is no search in the logs visible, this is just the startTLS, followed by the bind operation but no startTLS at all.

So I'm stumped without seeing some more data, are you OK with running a simple PAM test client for test purposes under strace?

**Comment by brotaxt** [comment] 2017-11-20 14:03
Unfortunately I must censor all data cause of data privacy protection. I can run the pam client, but I must check the whole log for sensitive data before posting it here. 

The ldap conenction to the IPA-Server works as expected without the module. 

Maybe Ive cut the log too early, this is the full log:

[20/Nov/2017:14:56:54.495489098 +0100] conn=64 fd=108 slot=108 connection from CLIENT_IP to SERVER_IP
[20/Nov/2017:14:56:54.495670094 +0100] conn=64 op=0 EXT oid="1.3.6.1.4.1.1466.20037" name="start_tls_plugin"
[20/Nov/2017:14:56:54.495703769 +0100] conn=64 op=0 RESULT err=0 tag=120 nentries=0 etime=0
[20/Nov/2017:14:56:54.498245330 +0100] conn=63 op=1 BIND dn="" method=sasl version=3 mech=GSSAPI
[20/Nov/2017:14:56:54.499722840 +0100] conn=63 op=1 RESULT err=14 tag=97 nentries=0 etime=0, SASL bind in progress
[20/Nov/2017:14:56:54.501267834 +0100] conn=64 TLS1.0 256-bit AES
[20/Nov/2017:14:56:54.501471619 +0100] conn=63 op=2 BIND dn="" method=sasl version=3 mech=GSSAPI
[20/Nov/2017:14:56:54.502417588 +0100] conn=63 op=2 RESULT err=0 tag=97 nentries=0 etime=0 dn="krbprincipalname=ldap/SERVERNAME@DOMAIN.de,cn=services,cn=accounts,dc=DOMAIN,dc=de"
[20/Nov/2017:14:56:54.504648951 +0100] conn=63 op=3 SRCH base="" scope=0 filter="(objectClass=*)" attrs="supportedControl supportedExtension"
[20/Nov/2017:14:56:54.505747503 +0100] conn=64 op=1 BIND dn="uid=USERNAME,cn=users,cn=accounts,dc=DOMAIN,dc=de" method=128 version=3
[20/Nov/2017:14:56:54.505914063 +0100] conn=63 op=3 RESULT err=0 tag=101 nentries=1 etime=0
[20/Nov/2017:14:56:54.506597074 +0100] conn=64 op=1 RESULT err=0 tag=97 nentries=0 etime=0 dn="uid=USERNAME,cn=users,cn=accounts,dc=DOMAIN,dc=de"
[20/Nov/2017:14:56:54.507082692 +0100] conn=63 op=4 SRCH base="" scope=0 filter="(objectClass=*)" attrs="supportedControl supportedExtension"
[20/Nov/2017:14:56:54.508295960 +0100] conn=63 op=4 RESULT err=0 tag=101 nentries=1 etime=0
[20/Nov/2017:14:56:54.509207098 +0100] conn=63 op=5 EXT oid="2.16.840.1.113730.3.5.12" name="replication-multimaster-extop"
[20/Nov/2017:14:56:54.509714741 +0100] conn=63 op=5 RESULT err=0 tag=120 nentries=0 etime=0
[20/Nov/2017:14:56:54.514830602 +0100] conn=63 op=6 EXT oid="2.16.840.1.113730.3.5.5" name="replication-multimaster-extop"
[20/Nov/2017:14:56:54.516055612 +0100] conn=63 op=6 RESULT err=0 tag=120 nentries=0 etime=0
[20/Nov/2017:14:56:54.543416908 +0100] conn=63 op=7 EXT oid="2.16.840.1.113730.3.5.12" name="replication-multimaster-extop"
[20/Nov/2017:14:56:54.543771630 +0100] conn=63 op=7 RESULT err=0 tag=120 nentries=0 etime=0
[20/Nov/2017:14:56:54.546160979 +0100] conn=63 op=8 EXT oid="2.16.840.1.113730.3.5.5" name="replication-multimaster-extop"
[20/Nov/2017:14:56:54.546854251 +0100] conn=64 op=2 UNBIND
[20/Nov/2017:14:56:54.546868863 +0100] conn=64 op=2 fd=108 closed - U1
[20/Nov/2017:14:56:54.549625186 +0100] conn=63 op=8 RESULT err=0 tag=120 nentries=0 etime=0
[20/Nov/2017:14:57:54.563899855 +0100] conn=63 op=9 UNBIND
[20/Nov/2017:14:57:54.563925239 +0100] conn=63 op=9 fd=68 closed - U1

**Comment by brotaxt** [comment] 2017-11-21 10:21
I've tested the getpwnam() function with the following code:

/* pasname.c */
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include </usr/include/pwd.h>
#include <string.h>
int main(int argc, char *argv[]) {
   struct passwd *pas_ptr;
   if( argc != 2 ) {
      fprintf(stderr, "Usage: %s Name\n", argv[0]);
      exit (EXIT_FAILURE);
   }
  /* Alternativ mit getpwuid() :                       */
  /* pas_ptr=getpwuid( strtoul(argv[1], NULL, 10) );   */
   pas_ptr=getpwnam(argv[1]);
   if(pas_ptr == NULL) {
      printf("Konnte nichts über %s ermitteln\n", argv[1]);
      exit (EXIT_FAILURE);
   }
   printf("Folgende Angaben wurden ermittelt: \n");
   printf("Benutzername     : %s\n", pas_ptr->pw_name);
   printf("Benutzernummer   : %d\n", pas_ptr->pw_uid);
   printf("Gruppennummer    : %d\n", pas_ptr->pw_gid);
   printf("Kommentar        : %s\n", pas_ptr->pw_gecos);
   printf("Loginverzeichnis : %s\n", pas_ptr->pw_dir);
   printf("Loginshell       : %s\n", pas_ptr->pw_shell);
   return EXIT_SUCCESS;
}

you@host > gcc -Wall -o pasname pasname.c
you@host > ./pasname admin

host:~ # ./pasname admin
Folgende Angaben wurden ermittelt:
Benutzername     : admin
Benutzernummer   : 1000
Gruppennummer    : 1001
Kommentar        : Administrator
Loginverzeichnis : /home/admin
Loginshell       : /bin/bash

This seems to work.

**Comment by jhrozek** [comment] 2018-01-17 14:48
I tried to relax the group resolving conditions in the 1.2 release I just published. Could you give that a try? If that still doesn't work, let's try some more debugging..

**Comment by jhrozek** [comment] 2018-05-06 18:18
Since there was no reply for quite some time, I'm closing the issue.

Please reopen if the issue is still valid.

**Closed as completed by jhrozek** 2018-05-06 18:18 UTC
Labels: question
